# Generated by Django 4.2 on 2025-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
