# Generated by Django 4.2 on 2025-11-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_student_application_status_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, to='crm.tag'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(blank=True, max_length=30)),
                ('to_number', models.CharField(blank=True, max_length=30)),
                ('message_body', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='in', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='crm.lead')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='crm.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
