# Generated by Django 5.2.8 on 2025-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='student',
        ),
        migrations.AddField(
            model_name='lead',
            name='ad_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='adset_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='fb_lead_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('manual', 'Manual'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.DeleteModel(
            name='FollowUpTask',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
    ]
